[package]
name = "bartender"
version = "0.1.0"
edition = "2021"

[features]
async-std = ["dep:async-std"]
test = ["async-std"]

[dependencies]
async-std = { version = "1.13.0", optional = true}

[dev-dependencies]
smol = "2.0.2"
